# Generated by Django 5.2.4 on 2026-04-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customerbookinginfo_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Administrator')], default='customer', max_length=50)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ROLE_CHANGE', 'Role Change'), ('LOGIN', 'Login')], max_length=50)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelServices',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_service', models.CharField(blank=True, db_column='service_name', max_length=225, null=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('room_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=225, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_key', models.CharField(max_length=100, unique=True)),
                ('content_value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_content',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customerbookinginfo',
            options={'managed': False, 'ordering': ['-booking_date']},
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel_info',
        ),
    ]
