# Generated by Django 5.2.4 on 2026-04-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user_auditlog_hotelservices_roomprice_sitecontent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerbookinginfo',
            table='booking_info',
        ),
    ]
