# Generated by Django 5.2.4 on 2026-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_customerbookinginfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('floor_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(blank=True, max_length=225, null=True)),
                ('current_status', models.CharField(choices=[('empty_clean', 'Empty Clean'), ('empty_dirty', 'Empty Dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('reserved', 'Reserved')], default='empty_clean', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor_number', 'room_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_assignments',
                'managed': False,
            },
        ),
    ]
