# Generated by Django 5.2.4 on 2025-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesRef',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
            ],
            options={
                'db_table': 'ImagesRef',
                'managed': False,
            },
        ),
    ]
