# Generated by Django 5.2.4 on 2025-08-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesref',
            options={'managed': True},
        ),
    ]
