# Generated by Django 5.2.4 on 2025-08-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_imagesref_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesref',
            options={'managed': False},
        ),
    ]
