# Generated by Django 5.2.4 on 2025-10-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_imagesref_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('star_rating', models.IntegerField()),
                ('hotel_address', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ImagesRef',
        ),
    ]
